### ISSUE TITLE
error: the following arguments are required: -m/--model, -l/--labelmap

### ISSUE THREAD

**Issue by Vierana** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#10]
i run the code that you have and i got error 

usage: newcameradetection.py [-h] -m MODEL -l LABELMAP
newcameradetection.py: error: the following arguments are required: -m/--model, -l/--labelmap

how i can fix that ?

**Comment by TannerGilbert** [comment]
You need to pass the path to the model and labelmap, e.g. `python newcameradetection.py -m <path to model> -l <path to labelmap>`
