### ISSUE TITLE
Object detection timestamp

### ISSUE THREAD

**Issue by sarzali07** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#2]
Hi

This is Sarfaraz, new to machine learning, As per reference to your video tutorial over Youtube title as Tensorflow Object Detection Tutorial #3 - Create your own object detector
I just want to know is there any way to save timestamp of detect object. If so can you let me know to what to change to code to save timestamp of detected object over mysql.

I wish to hear from you as soon as possible.

Regards
Sarfaraz

**Comment by TannerGilbert** [comment]
You can get the timestamp using your favourite time library:
- https://stackoverflow.com/questions/13890935/does-pythons-time-time-return-the-local-or-utc-timestamp

Then you can save the objects and timestamp into SQL.

Pseudocode
```python
output_dict = run_inference_for_single_image(image_np_expanded, detection_graph)
timestamp = #<get time>
# save into sql 
```
