### ISSUE TITLE
Issue while Loading the model

### ISSUE THREAD

**Issue by lakshaychhabra** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#3]
Hey I am encountering an issue while loading the model, any idea how to resolve it?

"INFO:tensorflow:Saver not created because there are no variables in the graph to restore"

I am sure I am loading right file from right directory.

**Comment by TannerGilbert** [comment]
The following issue suggests that you might need to install nomkl
https://github.com/tensorflow/hub/issues/337
