### ISSUE TITLE
Coco API installation in Windows giving error

### ISSUE THREAD

**Issue by UnnatiBabruwad** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#4]
Hey!
 The command used to install COCO api : pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"

is giving error:

![Screenshot (111)](https://user-images.githubusercontent.com/35571250/79820548-25cb9780-83aa-11ea-9fec-3834562775c2.png)

Please help.
Thanks

**Comment by TannerGilbert** [comment]
You need to install Microsoft Visual C++ >=14.0 as suggested in the error message. https://visualstudio.microsoft.com/downloads/
