### ISSUE TITLE
NotFoundError: data/mscoco_label_map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by Rohithv07** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#5]
While I do Load lable map
`PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)`

I get a NotFoundError

Iam doing this work in Google Colab

Error

`NotFoundError                             Traceback (most recent call last)
<ipython-input-12-681a3220bf6c> in <module>()
      1 # List of the strings that is used to add correct label for each box.
      2 PATH_TO_LABELS = 'data/mscoco_label_map.pbtxt'
----> 3 category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     77                                            "File isn't open for reading")
     78       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 79           self.__name, 1024 * 512)
     80 
     81   def _prewrite_check(self):

NotFoundError: data/mscoco_label_map.pbtxt; No such file or directory`

**Comment by TannerGilbert** [comment]
The path to the labelmap file isn't correct. Are you working inside the object_detection folder?

**Comment by Rohithv07** [comment]
![Capture](https://user-images.githubusercontent.com/36880893/82986038-bbde8780-a012-11ea-87b3-171108dcbae2.PNG)

Is this the file talking about?

**Comment by TannerGilbert** [comment]
No. You can find [the file](https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt) inside the object_detection/data folder.
